title: Thought Journeys
description: Place for thinkings on various subjects, mostly in the cybersecurity space.
author: Kyle B
logo: "https://azotheblue.github.io/Blog/static/img/avatar.jpg"
github: 
about: Curious Adventurer of New Things

baseurl: "/Blog"
url: ""

allowsearch: true

disqus_shortname: 
google_analytics: 

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
